### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by a-y-u-s-h** [BitsAiims2017/web#3]
Use this thread for all kinds of TODOs.

**Comment by a-y-u-s-h** [comment]
Components to be included : 

- [ ] Search box
- [ ] Spinning Loaders
- [ ] Tiles containing icons for add, edit, delete item.
- [ ] Something to easily categorise medicines like they do in [this pdf](https://files.gitter.im/BITS-Developers/Lobby/Lw5w/Essential-Medicine-List-AIIMS-Bhopal.pdf)

**Comment by coditva** [comment]
Pages to be made:

- [ ] Login page
- [ ] Logout button
- [ ] Add user. For admin only
- [ ] List users. Option for editing and deleting users. For admin only
- [ ] Items
  - [ ] List all
  - [ ] Add new
  - [ ] Item details page for each item
- [ ] Orders
  - [ ] List all orders. Options for editing and cancelling order
  - [ ] Add new
  - [ ] Pending orders
  - [ ] Order details page for each order

**Comment by a-y-u-s-h** [comment]
Aren't logout and login page same? User clicks log out and goes back to login page.

**Comment by coditva** [comment]
User clicks logout and you forget the login token you got when you logged in.
